### ISSUE TITLE
Octant crashes in Ubuntu on initial browser load: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by JoeJasinski** [vmware/octant#132] opened 2019-08-07 22:59 UTC
I tried using Octant 0.5.1 on Ubuntu 16.04 and got the following error when the octant loaded the browser (Firefox 68.0.1). I tried using both the Linux-64bit tar.gz download file and the .deb package; both resulted in the same error below. I also tried with Octant 0.5.0 with the same result. I don't know that it matters, as these seem to be compiled binaries, but I have installed Go 1.11.5. 

```
$ octant 
2019-08-07T17:53:44.959-0500	INFO	module/manager.go:75	registering action	{"component": "module-manager", "actionPath": "deployment/configuration", "module-name": "overview"}
2019-08-07T17:53:44.959-0500	INFO	api/content.go:52	Registering routes for overview
2019-08-07T17:53:44.960-0500	INFO	api/content.go:52	Registering routes for cluster-overview
2019-08-07T17:53:44.960-0500	INFO	api/content.go:52	Registering routes for configuration
2019-08-07T17:53:44.960-0500	INFO	dash/dash.go:335	Dashboard is available at http://127.0.0.1:37461

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x143d678]

goroutine 152 [running]:
github.com/vmware/octant/internal/kubeconfig.(*FSLoader).Load(0xc000253d70, 0xc0000432a0, 0x1c, 0x0, 0x0, 0x0)
	/go/src/github.com/vmware/octant/internal/kubeconfig/kubeconfig.go:76 +0x188
github.com/vmware/octant/internal/modules/configuration.(*kubeContextGenerator).Event(0xc0005d23c0, 0x1db8f80, 0xc000602690, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/vmware/octant/internal/modules/configuration/kube_context.go:103 +0x89
github.com/vmware/octant/internal/event.runGenerator(0x1db8f80, 0xc000602690, 0xc00049e120, 0xc00004e380, 0x1d9fe80, 0xc0005d23c0, 0xc000045344, 0x2b, 0xc000481e98, 0x1)
	/go/src/github.com/vmware/octant/internal/event/generator.go:89 +0x278
github.com/vmware/octant/internal/event.Stream.func1(0x1db8f80, 0xc000602690, 0xc00049e120, 0xc00004e380, 0xc000045344, 0x2b, 0xc000481e98, 0x1, 0xc000672000, 0x1d9fe80, ...)
	/go/src/github.com/vmware/octant/internal/event/generator.go:54 +0x9b
created by github.com/vmware/octant/internal/event.Stream
	/go/src/github.com/vmware/octant/internal/event/generator.go:53 +0x420
```

**Comment by lachie83** [comment] 2019-08-08 18:12
I'm seeing the same thing. What version of Kubernetes are you using @JoeJasinski?

I'm experiencing the same issue on v1.16.x. I have tested on a 1.14.x cluster and it does NOT give me this error.
```
$ octant version
Version:  0.5.1
Git commit:  e0397d2596a7575abf4ca9aeacafd92912d484e0
Built:  2019-08-06T19:40:35Z
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-alpha.3", GitCommit:"28e88e3f19c37242db1a456b1f45c543c4a540fe", GitTreeState:"clean", BuildDate:"2019-08-07T16:18:53Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-alpha.3", GitCommit:"28e88e3f19c37242db1a456b1f45c543c4a540fe", GitTreeState:"clean", BuildDate:"2019-08-07T16:08:39Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ octant
2019-08-08T11:06:45.663-0700	INFO	module/manager.go:75	registering action	{"component": "module-manager", "actionPath": "deployment/configuration", "module-name": "overview"}
2019-08-08T11:06:45.664-0700	INFO	api/content.go:52	Registering routes for overview
2019-08-08T11:06:45.664-0700	INFO	api/content.go:52	Registering routes for cluster-overview
2019-08-08T11:06:45.664-0700	INFO	api/content.go:52	Registering routes for configuration
2019-08-08T11:06:45.665-0700	INFO	dash/dash.go:335	Dashboard is available at http://127.0.0.1:51251

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x203d698]

goroutine 232 [running]:
github.com/vmware/octant/internal/kubeconfig.(*FSLoader).Load(0xc001235e00, 0xc00004010b, 0x2f, 0x0, 0x0, 0x0)
	/go/src/github.com/vmware/octant/internal/kubeconfig/kubeconfig.go:76 +0x188
github.com/vmware/octant/internal/modules/configuration.(*kubeContextGenerator).Event(0xc001286a40, 0x29b8620, 0xc0001a7050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/vmware/octant/internal/modules/configuration/kube_context.go:103 +0x89
github.com/vmware/octant/internal/event.runGenerator(0x29b8620, 0xc0001a7050, 0xc001394600, 0xc00138a000, 0x299f4e0, 0xc001286a40, 0xc001132084, 0x2b, 0xc001092098, 0x1)
	/go/src/github.com/vmware/octant/internal/event/generator.go:89 +0x278
github.com/vmware/octant/internal/event.Stream.func1(0x29b8620, 0xc0001a7050, 0xc001394600, 0xc00138a000, 0xc001132084, 0x2b, 0xc001092098, 0x1, 0xc0010920f0, 0x299f4e0, ...)
	/go/src/github.com/vmware/octant/internal/event/generator.go:54 +0x9b
created by github.com/vmware/octant/internal/event.Stream
	/go/src/github.com/vmware/octant/internal/event/generator.go:53 +0x420
```

**Comment by GuessWhoSamFoo** [comment] 2019-08-08 20:11
Can't seem to reproduce this with 0.5.1

```
➜  ~ k version                                                                                                                                                                                                                                                                                                                       [19/08/8| 1:09PM]
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-alpha.3.13+a51d5745960457", GitCommit:"a51d57459604577fb835a505c71a51fa45250d72", GitTreeState:"clean", BuildDate:"2019-08-08T00:12:31Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
➜  ~ octant version                                                                                                                                                                                                                                                                                                                  [19/08/8| 1:09PM]
Version:  0.5.1
Git commit:  e0397d2596a7575abf4ca9aeacafd92912d484e0
Built:  2019-08-06T19:40:35Z
➜  ~ octant                                                                                                                                                                                                                                                                                                                          [19/08/8| 1:09PM]
2019-08-08T13:09:58.939-0700    INFO    module/manager.go:75    registering action      {"component": "module-manager", "actionPath": "deployment/configuration", "module-name": "overview"}
2019-08-08T13:09:58.969-0700    INFO    plugin/manager.go:397   registered plugin "plugin-name" {"plugin-name": "pluginstub", "cmd": "/home/sfoo/.config/octant/plugins/pluginstub", "metadata": {"Name":"plugin-name","Description":"a description","Capabilities":{"SupportsPrinterConfig":[{"Group":"","Version":"v1","Kind":"Pod"}],"SupportsTab":[{"Group":"","Version":"v1","Kind":"Pod"}]}}}
2019-08-08T13:09:58.969-0700    INFO    api/content.go:52       Registering routes for overview
2019-08-08T13:09:58.970-0700    INFO    api/content.go:52       Registering routes for cluster-overview
2019-08-08T13:09:58.970-0700    INFO    api/content.go:52       Registering routes for configuration
2019-08-08T13:09:58.970-0700    INFO    dash/dash.go:335        Dashboard is available at http://127.0.0.1:46145
```

**Comment by bryanl** [comment] 2019-08-09 03:15
The code in question is 

```go
	for _, kubeContext := range rawConfig.Contexts {
		list = append(list, Context{Name: kubeContext.Name})
	}
```

Looks like either `rawConfig` or `rawConfig.Contexts` is nil. I'm going to see if I can reproduce.

**Comment by bryanl** [comment] 2019-08-09 16:55
We have a fix in master right now. This update will be in our next release (~August 20)

**Comment by lachie83** [comment] 2019-08-09 17:22
Thanks for the quick turn around @bryanl. Can you link the PR? I would like to take a look. I'll try building from master to test as well

**Comment by bryanl** [comment] 2019-08-09 17:33
> Thanks for the quick turn around @bryanl. Can you link the PR? I would like to take a look. I'll try building from master to test as well

https://github.com/vmware/octant/pull/144

This will change before we release 0.6, because I want to support contexts like `kubectl` does, but this is the gist.

**Comment by bryanl** [comment] 2019-08-14 12:15
#164 adds supports to handle contexts like `kubectl` does.

**Comment by wwitzel3** [comment] 2019-08-14 17:36
Thank you again for reporting this, closing this out. This issue is fixed in current master and will be available in the next binary release (~August 20th) as @bryanl mentioned.

**Closed by wwitzel3** 2019-08-14 17:36 UTC
Labels: bug

**Comment by JoeJasinski** [comment] 2019-08-14 23:49
Thank you!
