### ISSUE TITLE
Cant serve the dashboard over http (except for localhost)

### ISSUE THREAD

**Issue by Leluke** [vmware/octant#167] opened 2019-08-14 19:30 UTC
I have been trying to create a host machine that would serve the dashboard at some port so our devs could check our clusters using a single read only serviceaccount in this "bastion" for our clsuter.

I have managed to make the dashboard work locally only. I set up the .kube/config locally and started octant, and when I access 127.0.0.1:8900 I have access to the dashboard with all the resources listed.

If I try to do this with a different machine and try to access its external IP at the port the dashboard is being served, the page actually starts loading, but never actually shows anything.

No errors pop while running with the verbose option, and as far as I can tell, everything is properly set up.

**Comment by wwitzel3** [comment] 2019-08-14 19:57
Thank you for reporting this, we are aware of this issue, this is a duplicate of the issue reported in #152 . We have merged a fix for this in master #158 and it will be in our next binary release which is currently scheduled for ~ August 20th.

**Closed by wwitzel3** 2019-08-14 19:57 UTC
Labels: bug, duplicate
